services:
  duckdns:
    container_name: duckdns
    build: Dockerfile
    hostname: duckdns
    restart: unless-stopped
    environment:
      DUCKDNS_HOSTNAME: "YOUR_DOMAIN"
      DOCKDNS_TOKEN: "********************"
      WAIT_TIME: "300"
