version: "2"
services:
  ddns:
    container_name: ddns
    build: Dockerfile
    hostname: ddns
    restart: always
    environment:
      DUCKDNS_HOSTNAME: "YOUR_DOMAIN"
      DOCKDNS_TOKEN: "********************"
      WAIT_TIME: "300"